name: 🚀 Deployment to DEV

on:
  push:
    branches:
      [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🏗️ Build application
      uses: ./.github/actions/build
      with:
        APP_NAME: ${{ vars.APP_NAME }}
        APP_ENV: development
        APP_KEY: ${{ secrets.APP_KEY_DEV }}
        APP_DEBUG: true
        APP_URL: ${{ vars.APP_URL_DEV }}

        LOG_CHANNEL: json
        LOG_LEVEL: debug

        APP_LOCALE: pt

        DB_CONNECTION: mysql
        DB_HOST: localhost
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.DB_DATABASE_DEV }}
        DB_USERNAME: ${{ secrets.DB_USERNAME_DEV }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}

        JWT_SECRET: ${{ secrets.JWT_SECRET_DEV }}
        JWT_ALGO: ${{ secrets.JWT_ALGO }}
        JWT_EXPIRY: 3600
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 📝 Deploy application
      uses: ./.github/actions/deploy
      with:
        ftp-server: ${{ vars.FTP_SERVER_DEV }}
        ftp-user: ${{ secrets.FTP_USER_DEV }}
        ftp-password: ${{ secrets.FTP_PASSWORD_DEV }}
        SSH_USER: ${{secrets.SSH_USER}}
        SSH_HOST: ${{secrets.SSH_HOST}}
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        APP_URL: ${{vars.APP_URL_DEV}}