name: 📦 Restore Database from Backup

on:
  workflow_dispatch:
    inputs:
      BACKUP_FILE:
        description: 'Name of the backup file to restore (e.g., backup-2024-10-01-00.sql)'
        required: true
        default: ''

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: 🔐 Add server to known_hosts
        shell: bash
        run: |
          ssh-keyscan -p 2222 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🗂️ Check and Restore Database from Backup
        shell: bash
        run: |
          # Check if the backup file is specified
          if [ -z "${{ github.event.inputs.BACKUP_FILE }}" ]; then
            echo "Error: No backup file specified."
            exit 1
          fi

          # Connect to the server and restore the specified backup file
          ssh -p 2222 ${{ secrets.SSH_USER }} " \
            BACKUP_DIR='~/backups' && \
            BACKUP_PATH=\"\$BACKUP_DIR/${{ github.event.inputs.BACKUP_FILE }}\" && \
            if [ ! -f \"\$BACKUP_PATH\" ]; then \
              echo 'Error: Specified backup file does not exist in \$BACKUP_DIR.' && exit 1; \
            fi && \
            echo 'Restoring database tables from backup: ${{ github.event.inputs.BACKUP_FILE }}' && \
            TABLES=\$(mysql -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -Nse 'SHOW TABLES' ${{ secrets.DB_DATABASE }}) && \
            for table in \$TABLES; do \
              mysql -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e \"DROP TABLE IF EXISTS \\\$table\" ${{ secrets.DB_DATABASE }}; \
            done && \
            mysql -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_DATABASE }} < \"\$BACKUP_PATH\" && \
            echo 'Database tables restored successfully from ${{ github.event.inputs.BACKUP_FILE }}.' \
          "