name: 📦 Restore Database from Backup

on:
  workflow_dispatch:
    inputs:
      BACKUP_FILE:
        description: 'Name of the backup file to restore (e.g., backup-2024-10-01-00.sql)'
        required: true
        default: ''

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: 🔐 Add server to known_hosts
        shell: bash
        run: |
          ssh-keyscan -p 2222 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🗂️ Restore Database from Backup
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          BACKUP_FILE: ${{ github.event.inputs.BACKUP_FILE }}
        run: |
          # Check if the backup file is specified
          if [ -z "$BACKUP_FILE" ]; then
            echo "Error: No backup file specified."
            exit 1
          fi

          # Connect to the server and restore the specified backup file
          ssh -p 2222 $SSH_USER@$SSH_HOST << 'EOF'
            BACKUP_DIR="~/backups"
            BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

            # Check if the backup file exists
            if [ ! -f "$BACKUP_PATH" ]; then
              echo "Error: Specified backup file does not exist in $BACKUP_DIR."
              exit 1
            fi

            echo "Restoring database tables from backup: $BACKUP_FILE"

            # Drop all tables in the database
            TABLES=\$(mysql -u "$DB_USERNAME" -p"$DB_PASSWORD" -Nse 'SHOW TABLES' $DB_DATABASE)
            for table in \$TABLES; do
              mysql -u "$DB_USERNAME" -p"$DB_PASSWORD" -e "DROP TABLE IF EXISTS \\\$table" $DB_DATABASE
            done

            # Restore the database tables from the specified backup file
            mysql -u "$DB_USERNAME" -p"$DB_PASSWORD" "$DB_DATABASE" < "$BACKUP_PATH"

            echo "Database tables restored successfully from $BACKUP_FILE."
          EOF
