name: CI

on:
  pull_request:
    branches:
      [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install dependencies
        run: |
          rm -rf ./composer.lock
          composer install

      - name: Run tests and generate coverage
        run: |
          echo "Running PHPUnit..."
          ./vendor/bin/phpunit --coverage-text --configuration phpunit.xml --testsuite Unit > coverage.txt 2>&1
          echo "Finished running PHPUnit. Checking coverage.txt..."
          if [ -s coverage.txt ]; then
            echo "coverage.txt has content:"
            cat coverage.txt
          else
            echo "coverage.txt is empty or not created."
            exit 1
          fi

      - name: Check percentage
        run: |
          grep "Lines" coverage.txt > coverage_percent.txt
          if [ -s coverage_percent.txt ]; then
            echo "Content of coverage_percent.txt:"
            cat coverage_percent.txt
          else
            echo "coverage_percent.txt is empty or not created."
            exit 1
          fi
          coverage=$(grep -oP '(\d+\.\d+%)' coverage_percent.txt | sed 's/%//' | awk '{print $1 + 0}')
          if [[ $coverage -lt 90 ]]; then
            exit 1
          fi

      - name: Alert error
        if: failure()
        run: echo 'Tests failed.'

      - name: Alert success
        if: success()
        run: echo 'Tests succeded. Coverage is ${{ env.COVERAGE }}%'