name: CI

on:
  pull_request:
    branches:
      [main]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install dependencies
        run: |
          rm -rf ./composer.lock
          composer install
          
      - name: Run sniffer
        run: composer run:sniffer   

  tests:
    runs-on: ubuntu-latest
    needs: ["code-style"]
    strategy:
      matrix:
        suite: [Unit, Feature]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install dependencies
        run: |
          rm -rf ./composer.lock
          composer install

      - name: Run tests
        run: | 
          ./vendor/bin/phpunit --coverage-text --configuration phpunit.xml --testsuite ${{ matrix.suite }} > coverage.txt
          cat ./coverage.txt
      
      - name: Check percentage
        if: success()
        run: |
          grep "^[[:space:]]*Lines:" ./coverage.txt > coverage_percent.txt
          coverage=$(grep -oP '(\d+\.\d+%)' ./coverage_percent.txt | sed 's/%//' | awk '{print $1 + 0}')

          if [[ $coverage -lt 0 ]]; then
            echo 'Tests Failed because the coverage is $coverage% and this repository enforces 0% of coverage.'
            exit 1
          else
            echo 'Tests run succesfully with $coverage% coverage'
            exit 0
          fi